service: lambda-payload-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-offline
functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
